### ISSUE TITLE
Error with tank sizing after recent commit

### ISSUE THREAD

**Issue by daltonwstewart** [BioSTEAMDevelopmentGroup/BLocS#10]
Hi @yoelcortes 

Thanks for your recent commit to `evaluation.py`. Unfortunately it's resulting in an error with the fermentation tank sizing:

Traceback (most recent call last):

  Input In [4] in <cell line: 1>
    evaluate_IP('corn',10000)

  File ~/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/evaluation.py:1003 in evaluate_IP
    model = create_IPs_model(biorefinery)

  File ~/Dropbox/Stewart-Guest_Shared/Code/BLocS/blocs/incentives/evaluation.py:807 in create_IPs_model
    tea.V405.V = None # Override old batch volume setting (which allows number of batches to change)

  File ~/Dropbox/Stewart-Guest_Shared/Code/biosteam/biosteam/units/_batch_bioreactor.py:163 in V
    if V <= 1:

TypeError: '<=' not supported between instances of 'NoneType' and 'int'

Thanks for your help!

**Comment by yoelcortes** [comment]
Ahh, in the meanwhile I fix this up in BioSTEAM, could you update the code to:

```python
V405._V = None # use ._V instead of .V
```

Thanks!

**Comment by daltonwstewart** [comment]
Got it, thanks!
