### ISSUE TITLE
Corn biorefinery parameters

### ISSUE THREAD

**Issue by daltonwstewart** [BioSTEAMDevelopmentGroup/BLocS#3]
One last issue today,

We talked about which uncertain parameters to include for each biorefinery, and 2 we mentioned for the corn biorefinery were the boiler/turbogenerator efficiency and the fermentation efficiency.

I know that the corn biorefinery is a net consumer of electricity, so I think we can ignore the BT efficiency since electricity generation will occur outside the biorefinery. (it doesn't even seem like there is a BT object for the biorefinery?)

I looked into changing the fermentation efficiency, but it looks like the corn biorefinery is set up a little differently than the other two. I found Saccharification and Liquefaction objects (?), but I'm not sure how to call the efficiency to vary as a parameter. If you think it's worth it, can we adjust these objects so we can vary the efficiency? Let me know what you think, thanks!

**Comment by yoelcortes** [comment]
Hi Dalton, 

The efficiency for [Liquefaction](https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/blob/08c48b498485a3545399381857d7b7fca8dc2feb/BioSTEAM%202.x.x/biorefineries/corn/units.py#L166) and [Fermentor](https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/blob/08c48b498485a3545399381857d7b7fca8dc2feb/BioSTEAM%202.x.x/biorefineries/corn/units.py#L217) objects are available in their `reaction` attribute as [Reaction](https://thermosteam.readthedocs.io/en/latest/reaction/Reaction.html) objects.

You can change the efficiency by `<Unit>.reaction.X = efficiency`.

Hope this helps!
Thanks,

**Comment by daltonwstewart** [comment]
Got it! Thanks, Yoel!
