### ISSUE TITLE
Help setting up evaluate_across_coordinate() function

### ISSUE THREAD

**Issue by daltonwstewart** [BioSTEAMDevelopmentGroup/BLocS#4]
Hi @yoelcortes,

I'm having a little trouble with using `model.evaluate_across_coordinate()` in my new `evaluation.py` file. I can't figure out how the parameter should be named in the function so that it can use it. I tried naming it according to how it shows up in the `parameters` list and based on the parameter setter function, but neither worked.

I'm trying to set up a function here:
https://github.com/BioSTEAMDevelopmentGroup/BLocS/blob/443c65bd7de6a088865a9d1c1333899e4b32d963/blocs/incentives/evaluation.py#L834

That needs to reference this parameter:
https://github.com/BioSTEAMDevelopmentGroup/BLocS/blob/443c65bd7de6a088865a9d1c1333899e4b32d963/blocs/incentives/evaluation.py#L684

I think this should be an easy fix, and if you help me with this one I can figure out how to reference the rest of the parameters I need on my own. Please let me know if you need more information. Thank you!

**Comment by yoelcortes** [comment]
Hi Dalton, if you have a moment after the group meeting, I'd be happy to help out then (it should take like 15 min in person). No worries if not, I'll look into it sometime today or tomorrow

**Comment by daltonwstewart** [comment]
Sounds good! I'll see you after group meeting!
