### ISSUE TITLE
Changing incentive start years and other issues

### ISSUE THREAD

**Issue by daltonwstewart** [BioSTEAMDevelopmentGroup/BLocS#5]
Hi @yoelcortes 

I just finished making the changes we discussed yesterday related to incentive start years. You will see in [tax_incentives.py](https://github.com/BioSTEAMDevelopmentGroup/BLocS/blob/main/blocs/incentives/tax_incentives.py) that I added an additional `assess_incentive_arr` function to work with incentives that need array inputs because I was having trouble making your function work. If you want to adjust the file to only use one function, feel free.

I realized that we have another small issue related to the state-specific analysis, where we sometimes consider more than one incentive in a TEA at once. While we cap the value of individual incentives at the amount of tax assessed, I don't think there's anything in the code cap the value of all incentives applied to a particular tax at the amount of tax assessed. What's the quickest fix for this?

Also, we haven't implemented methods to output the contributions of important parameters (TCI, FCI, state income tax, property tax) as % of the MESP. The only time we need to do this is when using the `evaluate_IP` function, so we could add it as a metric there.

Relatedly, I tried using some functions within `evaluation.py` after updating the incentive start years, and I got errors with all feedstocks, related to "addending chemicals" or something like that.

Let me know if anything is unclear and what you want me to take care of. Thank you for your help with all of this.
Dalton

**Comment by yoelcortes** [comment]
@daltonwstewart,

Awesome! 

Regarding the sum of all tax incentives possibly being larger than the assessed tax, I fixed this by removing the incentive values from the assessed tax (so that the next incentive evaluated cannot be larger than the total assessed tax minus all other evaluated incentives).

I added the material cost as a metric to the model. This will allow you to calculate what fraction of the MFSP is the capital cost. You can use the following formulas:
* % Capital investment contribution to MFSP = 100 * (MFSP - material cost / ethanol production) / MFSP # This value will vary if MFSP is before or after incentive
* % Reduction from incentive = 100 * MFSP Reduction / MFSP baseline

Please feel free to add these as metrics in the code if you prefer, just make sure to use the right units of measure during calculation.

I got all the functions in evaluation.py to work. I also updated the blocs branch of BioSTEAM for better autosaving during Monte Carlo. Just "git pull origin blocs" in your local biosteam repo to get your code to work.

Hope this helps!
Thanks,

**Comment by yoelcortes** [comment]
@daltonwstewart, i almost forgot. You'll also need to include fixed operating cost, utility cost and co-product credits to get percent contribution of capital cost. I'll add these to the model later today.

**Comment by yoelcortes** [comment]
@daltonwstewart,

I added the "total_production_cost" method which accounts for variable and fixed operating costs and coproduct credits (and I removed the material cost metric). Now you should be able to get the contribution percentages as follows:

    % Capital investment contribution to MFSP = 100 * (MFSP - ethanol production cost) / MFSP # This value will vary if MFSP is before or after incentive
    % Reduction from incentive = 100 * MFSP Reduction / MFSP baseline

Hope this helps, 
Thanks!

**Comment by daltonwstewart** [comment]
Thanks @yoelcortes !

I took me a sec to wrap my head around this, but I got it! 

Is it possible to make these % breakdown calculations even more granular? For example, how much state income tax specifically contributes to MESP? Jeremy and I have been discussing revamping the methods to include % MESP contributions for the six broad incentive groups I define in the manuscript (so TCI, FCI, ethanol production equipment, income tax, ethanol production, and jobs). I realize those last two might be tricker to define a contribution to MESP for. Let me know what you think about this.

Thank you!

**Comment by yoelcortes** [comment]
Hi Dalton,

It is possible to do so to any level of detail, you just need to think about it in terms of NPV. For a given cash flow array of just the variable you are looking at (e.g., income tax), solve for the amount of revenue per year necessary to get an NPV of zero and divide that by the annual ethanol production. This would be equal to the MESP contribution. 

Alternatively, you can calculate the MESP, then recalculate it without the expenses (e.g., income tax or labor cost). The contribution to the MESP would be the difference between these values.

Thanks!

**Comment by daltonwstewart** [comment]
Hi @yoelcortes 

I think I'm still misunderstanding/overthinking this a bit.

I like the idea of just calculating the MESP without certain expenses and comparing that to the baseline MESP, so I added some methods to do so in `evaluation.py`, but there must be a step I'm forgetting about. My attempt at these methods was to set certain tax rates to zero, recalculate MESP, then compare this MESP to the baseline to determine the contribution of taxes to MESP (see [`inc_tax_contribution`](https://github.com/BioSTEAMDevelopmentGroup/BLocS/commit/d5f9ce552aec0b3cebcadad7e82455dbc5c3fbcd#diff-a6cbb79405377381b835716d65dfb66a3b531834d895451f228f6a55a7605bf0R633)). However, now I will only get 1 out of n simulations with nonzero tax outputs (see [this file](https://github.com/BioSTEAMDevelopmentGroup/BLocS/blob/main/blocs/incentives/results/IP.xlsx) if my explanation doesn't make sense), so it seems like I need to reset the tax rate to the original value at some point in the method. Could you help me implement this?

That technique works well for taxes, but I'm still at a bit of a loss for how to set up a method for the % contribution of ethanol production equipment to MESP, for example. I know I call this parameter with the `get_ETOH_eq` method, but I don't think it's a cashflow array. I also don't know how solve for the NPV with only this cashflow considered, because the `solve_price` method seems like it's set up pretty specifically to include all of the biorefinery's cashflows. Could you write up an example method to determine the contribution of ethanol production equipment to MESP, and then I can modify it for other parameters I need?

Thanks for your help with all this,
Dalton

**Comment by yoelcortes** [comment]
@daltonwstewart,

Sorry for the late reply! Regarding the first issue, just reset the parameter you set to zero back to the original value:

```python
# Previously it was:
# @model.metric(name='Income Tax Contribution to MFSP', units='%') 
# def inc_tax_contribution():
#       tea.state_income_tax = 0
#       return (MFSP_baseline.get() - solve_price())/MFSP_baseline.get() * 100

@model.metric(name='Income Tax Contribution to MFSP', units='%') 
def inc_tax_contribution():
        param = tea.state_income_tax
        tea.state_income_tax = 0
        value = (MFSP_baseline.get() - solve_price())/MFSP_baseline.get() * 100
        tea.state_income_tax = param
        return value
```

As for the second issue, I believe the code assumes that all equipment is ethanol production equipment (checkout `create_cornstover_tea` in `incentives_tea.py`).  So you can use the `cap_inv_contribution` metric instead. It get's a little tricky if you want to split up capital costs by equipment because of the way TEA is calculated, but if you really need this I can figure out a way.

Thanks!

**Comment by daltonwstewart** [comment]
Hi @yoelcortes 

The first issue is resolved, thanks so much.

Regarding the second issue, is the `cap_inv_contribution` metric (based on the `ethanol_production_cost` metric you wrote) determining the contribution of FCI or TCI? From what I can tell it should be TCI, but I want to check.

I know that we assume all equipment at the biorefinery is considered ethanol production equipment, but this is still different than TCI. If I calculate TCI, the value of ethanol production equipment, and the contribution of TCI to MESP, is it reasonable to determine the contribution of ethanol production equipment to MESP by multiplying the TCI contribution by the ethanol production/TCI ratio? Meaning:
```
@model.metric(name='Ethanol Production Equipment Contribution to MFSP, units='%')
ratio=get_ETOH_eq.get()/get_TCI.get()
return ratio*cap_inv_contribution.get()
```

Let me know what you think of this. Thanks!
Dalton

**Comment by yoelcortes** [comment]
Hi Dalton,

Hmm, first I'd like to note a couple of things to make sure we're on the same page:
* ~The capital investment contribution (as coded) also includes fixed operation costs (e.g., maintenance; these are computed based on capital costs).~ The capital investment contribution does not include fixed operating costs.
* The total depreciable capital (TDC) is the installed equipment cost plus warehouse, site development, and additional piping.
* The fixed capital investment (FCI) is the TDC plus proratable costs, field expenses, construction, contingency, and other indirect costs. 
* The total capital investment (TCI) is the FCI plus the working capital (which is about 5%).

I think the way get_ETOH_eq is computed has an issue. For the corn/sugarcane biorefinery, this is the FCI. But for the cornstover biorefinery, this is the ~total depreciable capital (TDC)~ installed equipment cost. If we just want installed equipment cost, we might want to switch this to the following:

In both evaluation.py and incentives_tea.py:
```python
    # Before
    # if tea.lang_factor:
    #     ethanol_eq = 1e6 * tea.lang_factor * tea.ethanol_group.get_purchase_cost()
    # else:
    #     ethanol_eq = 1e6 * tea.ethanol_group.get_installed_cost()
    # return ethanol_eq

    # After
    ethanol_eq = 1e6 * tea.ethanol_group.get_installed_cost()
    return ethanol_eq
```

I'm not exactly sure what we are trying to show by the "ethanol equipment contribution", do we want to account for all factors of the equipment (including indirect costs), the depreciable capital, or just the installed equipment cost?

Thanks,

**Comment by daltonwstewart** [comment]
Hi Yoel,

The whole idea of all of these % contribution metrics relates to the groups of tax incentives I reference in the manuscript (e.g., incentives whose value is determined based on TCI, FCI, the value of specific equipment, volumetric ethanol production, amount of tax paid, # of jobs). To help characterize and justify the importance of these groups, I want to give readers a sense for the magnitude and % contribution to MESP of relevant parameters (so TCI, FCI, ethanol production equipment, income tax, wages).

So for non tax expenses (meaning ethanol equipment for example), I think it makes sense to account for all the ways they contribute to MESP. The same goes for capital investment. I hope my explanation makes sense. Are the metrics currently written to output things in this way?

**Comment by yoelcortes** [comment]
Hi Dalton,

Yeah, that sounds about right. For the ethanol equipment cost for tax incentives, I think we should change it to just the installed cost (not multiply by lang factor) as in the example. I don't think the tax incentive accounts for indirect costs of equipment. We just need to be clear in the manuscript that the contribution of ethanol equipment does not take into account indirect costs.

Other than this, I believe all the metrics are set up correctly for the % contributions.

Thanks!

**Comment by daltonwstewart** [comment]
Sounds good! One last clarification: is the output of the `cap_inv_contribution` metric a representation of the contribution of TCI to MESP? Thanks!

**Comment by yoelcortes** [comment]
Hi Dalton,

Sorry for the confusion, the `cap_inv_contribution` metric does not include fixed operating costs (only the TCI). I just crossed out the bullet point in my previous comment where I state incorrectly that it does include FOC. Yeah, it is a good representation of the TCI contribution (and just the TCI) :)

Thanks!
