### ISSUE TITLE
Standardize dollar years

### ISSUE THREAD

**Issue by daltonwstewart** [BioSTEAMDevelopmentGroup/BLocS#7]
Hi @yoelcortes 

Something that came up in a discussion between Jeremy and I is the dollar years used in each biorefinery TEA (e.g., we might say MESP is reported in 2016 dollars). Is this information included with the biorefinery models somewhere? Jeremy would like to standardize all the biorefineries I'm considering to the same year if possible. Please let me know.

Thanks,
Dalton

**Comment by yoelcortes** [comment]
That's a good point. We can set the Chemical Engineering Plant Cost Index by setting `bst.CE` **after loading a biorefinery for the first time** (e.g., setting bst.CE after creating the tea object would work). We have a dictionary of cost indices in BioSTEAM too: `biosteam.design_tools.CEPCI_by_year`. I believe we are using a CE of 567. We don't have any price indices for material costs, you would need to set prices of streams manually.

Thanks,

**Comment by daltonwstewart** [comment]
Got it, thank you!
