### ISSUE TITLE
Bug with assessed income tax

### ISSUE THREAD

**Issue by daltonwstewart** [BioSTEAMDevelopmentGroup/BLocS#9]
Hi @yoelcortes 

I've noticed a new bug with my [Assessed income tax](https://github.com/BioSTEAMDevelopmentGroup/BLocS/blob/main/blocs/incentives/evaluation.py#L603) metric that was previously working properly. Now it either 1) only outputs a reasonable value for the first simulation, and then the rest of the outputs are 0, or 2) outputs a reasonable value for the first simulation, then outputs values that asymptotically approach a slightly different value for this rest of the simulations. Is this another instance where I need to reset a parameter within the metric? 

Thanks for looking into it,
Dalton

**Comment by yoelcortes** [comment]
Hi Dalton, 

Yeah, there was another place where parameters were being set to zero. It is fixed now :)

Also, I set the price of ethanol (used to compute sales) to the baseline MESP to have the contributions more consistent.

Thanks!

**Comment by daltonwstewart** [comment]
Hi @yoelcortes 

I was looking through the manuscript again, and I'm wondering if there's still a bug with income tax. I noticed that the income tax results in Figure 6 (where we plot the effect of Incentive 12 across a range of income tax rates) look a little strange. They should be a straight horizontal line rather than slightly decreasing (e.g., at their most effective, incentives should make it as if the biorefinery is not paying tax, so the incentivized MESP at 0% tax rate should be the same as at 12%). 

From what I can tell, this bug is only happening for this across-parameter evaluation (all of the other results look reasonable). It seems as if the maximum value of income tax incentives may not be capped at the appropriate maximum value. How can we go about looking into this?
